examples/common/listener_mrp_client.c
Fatal typo: '=' instead of '=='.
=> bugfix issue 169: MRP regression: listener does not see talker

daemons/maap/common/maap_protocol.c, daemons/maap/common/maap_protocol.h, daemons/maap/linux/maap_linux.c
Signed-off-by: manjunathhadli <manjunath.hadli@vayavyalabs.com>
Changing the license from GPL to BSD for previously implemented MAAP daemon.
=> changed the file licenses from GPL to BSD.

daemons/gptp/common/avbts_message.hpp, daemons/gptp/common/ieee1588.hpp, daemons/gptp/common/ptp_message.cpp
Rejects Announce message with sourcePortIdentity same as my own
AVnu certification test 6.3a - PASS
Rejects Path Trace TLV with ClockIdentity same as mine
Implemented PathTraceTLV Parsing
Implemented PathTraceTLV Append/Search Operations
Added debug (print method) to ClockIdentity class
Corrected misc output format (printf), indentation issues
=> Fixed AVnu certification test failure 6.1a and 6.3a

documents/examples/AVB_Talker_Listener_Example_Setup.md
For the talker/listener example, I improved the documentation.
Now, it should be possible to setup two AVB instances by plain copy and paste.
I think it is helpful for newcomers.
=> Improved documentation for talker/listener example

examples/common/avb.c, examples/common/avb.h, examples/jackd-talker/jackd_talker.c, examples/simple_talker/simple_talker.c
There is a critical segmentation fault which prevents that `simple_talker` and `jackd_talker` are working anymore.
`gptpinit()`: igb_mmap pointer is passed by value though its address is changed and should be updated in a global sense (not only within the function's scope).
Beside this problem, various minor warnings are fixed.
The corresponding issue is: #184 (though it's description is not adapted yet)
=> Fixed segmentation fault: pointer adress not passed by reference

daemons/maap/linux/Makefile, daemons/mrpd/Makefile, examples/common/Makefile, examples/jackd-listener/Makefile, examples/jackd-talker/Makefile, examples/live_stream/Makefile, examples/mrp_client/Makefile, examples/simple_listener/Makefile, examples/simple_talker/Makefile
Allow overriding the compiler/CC variable by using weak assignment to $(CC) and removing harcoded gcc entries. The maap, mrpd and mrp_control patches are cross-compile tested using a yocto build targetting a PPC and all changes are compile tested using native compile.
=> Cross compile support

examples/jackd-talker/jackd_talker.c
A pull request was made against master a while back for a fix that
was never applied to open-avb-next. There was some refactoring done
in open-avb-next, so when it was last merged with master, this fix
didn't have the refactor changes applied. Now it does.
=> Fix a jackd_talker error from last open-avb-next merge.

examples/jackd-talker/jackd_talker.c
This is pulling the change fixed in https://github.com/AVnu/Open-AVB/pull/247 to open-avb-next.
See https://github.com/AVnu/Open-AVB/pull/175 for discussion on the original fix.
=> Merge a jackd_talker fix from master.

daemons/gptp/linux/src/linux_hal_generic.cpp
On 2014-12-18 commit 5668e632c2063510b7f35e8a326c1622eab86325 introduced
a problem for users of the generic Linux HAL--some extremely large PHY
latency values (probably to offset latency introduced by a net sniffer)
were accidentally (I assume) committed. These cause low link delay values
to become negative.
This commit removes the preprocessor directives that replaced the original
latency values with the large ones.
=> Fix bogus PHY latency values in gPTP Linux HAL

kmod/igb/igb_ptp.c
Use timespec64 when necessary.
=> igb-avb: fix typo (timespec/timespec64)

lib/igb/igb.c, lib/igb/igb.h
libigb reads mac address from hardware but doesn't provide function to access it. This pull request adds such function.
=> Added function igb_get_mac_addr().

daemons/gptp/linux/src/ipcdef.hpp, daemons/gptp/windows/daemon_cl/ipcdef.hpp, examples/common/avb.c, examples/common/avb.h, examples/jackd-talker/jackd_talker.c, examples/simple_talker/simple_talker.c
It can be used to quickly get localtime calculated from current system time and values provided by gptp deamon (frequency offsets and phase offsets).
=> gptplocaltime() function added.

lib/avtp_pipeline/platform/Linux/rawsock/igb_rawsock.c, lib/avtp_pipeline/platform/Linux/rawsock/igb_rawsock.h, lib/avtp_pipeline/platform/Linux/rawsock/openavb_rawsock.c, lib/avtp_pipeline/platform/x86_i210/openavb_ether_hal.c, lib/avtp_pipeline/platform/x86_i210/openavb_ether_hal.h
This allows to run many talkers without any changes to igb_avb driver.
=> Create pool of tx buffers from multiple dma pages.

examples/mrp_client/mrpdhelper.h
Somehow an error value was missing from the enumerated list of MSRP failure codes.
=> examples: mrp_client: BUGFIX, add missing MSRP failure code

lib/avtp_pipeline/intf_ctrl/ctrl_talker.ini, lib/avtp_pipeline/intf_echo/echo_talker.ini, lib/avtp_pipeline/intf_echo/echo_talker_auto.ini, lib/avtp_pipeline/intf_null/null_talker.ini, lib/avtp_pipeline/intf_tonegen/tonegen_talker.ini, lib/avtp_pipeline/intf_viewer/latency_talker.ini, lib/avtp_pipeline/platform/Linux/intf_alsa/aaf_file_talker.ini, lib/avtp_pipeline/platform/Linux/intf_alsa/aaf_talker.ini, lib/avtp_pipeline/platform/Linux/intf_alsa/alsa_talker.ini, lib/avtp_pipeline/platform/Linux/intf_mjpeg_gst/mjpeg_gst_talker.ini, lib/avtp_pipeline/platform/Linux/intf_mpeg2ts_file/mpeg2ts_file_talker.ini, lib/avtp_pipeline/platform/Linux/intf_mpeg2ts_gst/mpeg2ts_gst_talker.ini, lib/avtp_pipeline/platform/Linux/intf_wav_file/wav_file_talker.ini, lib/avtp_pipeline/platform/Linux/tl/openavb_tl_osal.c, lib/avtp_pipeline/tl/openavb_talker_no_endpoint.c, lib/avtp_pipeline/tl/openavb_tl.c, lib/avtp_pipeline/tl/openavb_tl_pub.h
Details: You can specify VLAN Identifier in talker ini file.
Syntax is vlan_id = 5; Default value is 2 for both class A and class B streams.
=> New: VLAN ID can be configured for no endpoint builds.

lib/avtp_pipeline/avtp/openavb_avtp.c, lib/avtp_pipeline/avtp/openavb_avtp_time.c, lib/avtp_pipeline/platform/Linux/endpoint/openavb_endpoint_client_osal.c, lib/avtp_pipeline/platform/Linux/endpoint/openavb_endpoint_server_osal.c, lib/avtp_pipeline/platform/Linux/intf_h264_gst/openavb_intf_h264_gst.c, lib/avtp_pipeline/platform/Linux/intf_mjpeg_gst/openavb_intf_mjpeg_gst.c, lib/avtp_pipeline/platform/Linux/intf_mpeg2ts_file/openavb_intf_mpeg2ts_file.c, lib/avtp_pipeline/platform/Linux/openavb_os_services_osal.h, lib/avtp_pipeline/platform/Linux/openavb_time_osal.c, lib/avtp_pipeline/platform/Linux/rawsock/ring_rawsock.c, lib/avtp_pipeline/tl/openavb_listener.c, lib/avtp_pipeline/tl/openavb_talker.c
Details: Used macros for print formating eg. PRIu64 or PRIu32 so the expected
and supplied formats match. Also changed format specifiers when they weren't matching
expected format: eg. "llu" to "lu".
=> Fixes: Wrong output from log messages on 64bit machines.

daemons/gptp/linux/src/linux_hal_i210.cpp
From I210 datasheet section
7.8.3.3.3 "Synchronized Output Clock on SDP Pins":
The clock out drives initially a logical '0' level on the selected SDP.
If the TSAUXC.ST0/1 flag is cleared, it happens instantly when setting the
TSAUXC.EN_CLK0/1 bit.
Otherwise it happens when the SYSTIM is >= the TRGTTIM.
Before the fix, when stopping PPS, only the SDP pin is disabled.
Therefore when starting PPS again, as soon as the SDP pin is enabled,
the clock output starts.
This fix will correctly clear the TSAUXC.ST0/1 and TSAUXC.EN_CLK0/1 bits
when stopping PPS. This will ensure that the clock output only happen
when the SYSTIM is >= the TRGTTIM.
Signed-off-by: Roland Hii <roland.king.guan.hii@intel.com>
=> daemon_cl: Fixes PPS out-of-phase issue.

kmod/igb/kcompat.c, kmod/igb/kcompat.h
Sync kernel compatibility code for older kernel versions with upstream.
Signed-off-by: Todd Fujinaka <todd.fujinaka@intel.com>
=> igb_avb: sync kcompat.[ch] with upstream

kmod/igb/igb_main.c, kmod/igb/kcompat.h
I got a problem that 32-bit application(talker) fails to run on 64-bit kernel.
There are two problems.
* 'compat_ioctl' callback should be added on file_operations.
* If memory address for DMA is over 32bits, user application calls 'mmap()' with wrong address.<BR/>
In detail,<BR/>
Application queries memory address for 'mmap()' with ioctl().<BR/>
But if the address for DMA is reserved bigger than 4GB(32bits),<BR/>
application gets clipped address on the result of ioctl().<BR/>
After then, wrong address is used at calling 'mmap()'.
And one more trivial patch is added for typo.
=> igb_avb: Support 32bit app on 64bit kernel.

daemons/mrpd/msrp.c, daemons/mrpd/msrp.h, daemons/mrpd/tests/simple/mrp_doubles.c, daemons/mrpd/tests/simple/mrp_doubles.h, daemons/mrpd/tests/simple/msrp_tests.cpp
This set of checkins restricts listener attribute merging to only occur in the direction of listener attribute propagation. It address issue #338 where a received PDU from a switch overwrote the declared listener attribute.
=> MRP: correct listener attribute merge bug

daemons/gptp/common/avbts_message.hpp, daemons/gptp/common/avbts_port.hpp, daemons/gptp/common/gptp_cfg.cpp, daemons/gptp/common/gptp_cfg.hpp, daemons/gptp/common/ieee1588port.cpp, daemons/gptp/common/ptp_message.cpp, daemons/gptp/gptp_cfg.ini, daemons/gptp/linux/src/daemon_cl.cpp
Fixes Issue #135 
On the followUP messages, it is checked if the amount of wrong syncMessages is over a threshold, and if that is true, gPTP switches to master.
This patch was validated using the UNH-IOL tools for gPTP.
=> Fix wrong behaviour with wrong seqIDs on sync messages 

daemons/gptp/common/avbts_message.hpp, daemons/gptp/common/avbts_port.hpp, daemons/gptp/common/gptp_cfg.hpp, daemons/gptp/common/ieee1588port.cpp, daemons/gptp/common/ptp_message.cpp, daemons/gptp/gptp_cfg.ini, daemons/gptp/linux/src/daemon_cl.cpp
This patch fixes Issue #138 and potentially others as well. There are other open issues that are related to handle fups/resp lost messages and making gPTP not being asCapable. The Issue #138 was fixed and I am retesting the whole thing to see if at this point nothing got broken and if there are other ones fixed as well. 
I will be posting the other results directly on the open issues if I have good news. For now I want to create the pull request (which is quite small - but required lot of investigation and testing) so people can review and we can move forward and integrate this into Avnu's repo.
=> Handles lost of Resp and Fup messages

daemons/gptp/common/ptp_message.cpp
This patch adds a few conditions to abort the PTPMessagePathDelayRespFollowUp::processMessage method, which will have the consequence of disabling the AsCapable flag, since the PDELAY_RESP_RECEIPT_TIMEOUT will expire. 
The conditions are:
- Request/Response clockID must be the same
- Request/Response port number must be the same
- Response/FUP sourcePortIdentity must be the same
This patch addresses all the issues reported on Issue #139
=> Adding more conditions to set ASCapable to false

daemons/gptp/README_AVNU_AP.txt, daemons/gptp/common/ap_message.cpp, daemons/gptp/common/avbap_message.hpp, daemons/gptp/common/avbts_clock.hpp, daemons/gptp/common/avbts_message.hpp, daemons/gptp/common/avbts_osnet.hpp, daemons/gptp/common/avbts_persist.hpp, daemons/gptp/common/avbts_port.hpp, daemons/gptp/common/debugout.hpp, daemons/gptp/common/gptp_log.cpp, daemons/gptp/common/gptp_log.hpp, daemons/gptp/common/ieee1588.hpp, daemons/gptp/common/ieee1588clock.cpp, daemons/gptp/common/ieee1588port.cpp, daemons/gptp/common/ptp_message.cpp, daemons/gptp/common/ptptypes.hpp, daemons/gptp/linux/build/Makefile, daemons/gptp/linux/src/daemon_cl.cpp, daemons/gptp/linux/src/linux_hal_common.cpp, daemons/gptp/linux/src/linux_hal_common.hpp, daemons/gptp/linux/src/linux_hal_generic.cpp, daemons/gptp/linux/src/linux_hal_intelce.cpp, daemons/gptp/linux/src/linux_hal_persist_file.cpp, daemons/gptp/linux/src/linux_hal_persist_file.hpp, daemons/gptp/windows/daemon_cl/IPCListener.cpp, daemons/gptp/windows/daemon_cl/Stoppable.hpp, daemons/gptp/windows/daemon_cl/daemon_cl.cpp, daemons/gptp/windows/daemon_cl/ipcdef.hpp, daemons/gptp/windows/daemon_cl/windows_hal.cpp, run_gptp.sh
A fairly large set of changes to gPTP to support the AVnu Automotiive Profile. Details of the readme are:
This readme covers only the additional features added to the gPTP daemon 
to support the AVnu Automotive Profile (AP). 
- In general all features of the AP support for a Slave device have been 
implemented with the following exceptions. 
- Windows OS platform code has not been implemented.
- Detailed list of the AP implementation includes
- Configuration		
- Static gPTP values (AutoCDS 6.2.1)
- Persistent gPTP values (AutoCDS 6.2.2)
- Management Updated Values (AutoCDS 6.2.3)
- Signalling Message Configuration (AutoCDS 6.2.4)
- Followup TLV (AutoCDS 6.2.5)
- Required Values for gPTP (AutoCDS 6.2.6)
- Operation
- Disable BMCA (AutoCDS 6.3)
- No verification of sourcePortIdentity …
=> AVnu automotive profile for gPTP

daemons/gptp/common/avbts_port.hpp, daemons/gptp/common/ieee1588.hpp, daemons/gptp/common/ieee1588port.cpp, daemons/gptp/common/ptp_message.cpp
This pull request adds the PDelayRequest Halt feature when gPTP is receiving multiple responses from different sources. In this case, gPTP is supposed to halt PDelayRequest transmission for 5 minutes. 
Fixes Issue #302
=> Halt PDelayReq messages if received multiple responses from different sources

daemons/gptp/common/ieee1588port.cpp
The Path Delay timer used for issuing Path Delay Request messages was not being set properly.
=> Fix issue with PDelay timer not being set properly

daemons/gptp/common/avbts_osnet.hpp, daemons/gptp/common/avbts_port.hpp, daemons/gptp/common/ieee1588.hpp, daemons/gptp/common/ieee1588clock.cpp, daemons/gptp/common/ieee1588port.cpp, daemons/gptp/linux/src/linux_hal_common.cpp, daemons/gptp/linux/src/linux_hal_common.hpp
Created a link_thread to monitor the NIC status;
Created two extra events on IEEEPort::processEvents to
handle the link up/down state transitions;
On link up, the HWTimestamper init is called. On link down, it is
just being logged the state transition.
This commit is based on the automotive-profile branch and fixes Issue #254.
=> Handle link up/down events

daemons/gptp/common/ptp_message.cpp, daemons/gptp/linux/src/platform.cpp, daemons/gptp/linux/src/platform.hpp, daemons/gptp/windows/daemon_cl/platform.cpp, daemons/gptp/windows/daemon_cl/platform.hpp
When using 64 bit words, the function byte_swap64 is used. This
function assumes the machine's endianness and because of that it is
not portable.
This patch adds two new functions to deal with the problem of converting
64 bit words between host/network order without assuming the host endianness.
Two byte_swap64 calls were replaced by these two new functions in
PTPMessageCommon::buildCommonHeader and
PTPMessageCommon::buildPTPMessage.
This commit addresses Issue #243
=> 64 bit words network/host order conversion

daemons/gptp/common/ieee1588port.cpp
If priority1 is set to 255, gPTP must not send any sync
or follow_up messages. gPTP may continue send announce
messages even when priority1 is 255, and BCMA should guarantee
that this device is not a gm.
Reference: IEEE 802.1AS Subclause 10.3.12
=> Continue sending announce when priority1 is 255

daemons/gptp/common/ptp_message.cpp
Previously followup TLV offset was incorrect in the code - the PTP header
length was missing
This patch adds in the length of the PTP header
=> Fix TLV parse offset

.gitmodules
The default git@ url doesn't seem to work.
=> Fix cpputest url in .gitmodules

daemons/gptp/linux/src/linux_hal_i210.cpp, examples/common/avb.c, examples/jackd-talker/jackd_talker.c, examples/simple_talker/simple_talker.c, lib/avtp_pipeline/openavb_common/avb.c
Fix for #396
pci_connect seems to be duplicated 5 times...
=> Fix for #396

daemons/gptp/common/ptp_message.cpp
Hello,
this patch fixes a memory leak in `buildPTPMessage()`:
When a message with unset transport_specific flag is received, `buildPTPMessage()` will immediately return NULL, without freeing any previously allocated resources.
This patch changes the function so that the check is performed before a PortIdentity is allocated, and instead of returning NULL immediately, jumps to the cleanup code at the end of the function (which is also used in case of other error conditions).
To verify the memory leak and the fix, the attached source can be used (the code will send 1,000,000 announce message with unset transport_specific flag).
[unspecific_memory_leak.zip](https://github.com/AVnu/Open-AVB/files/302053/unspecific_memory_leak.zip)
=> Memory leak in buildPTPMessage()

daemons/gptp/common/avbap_message.hpp, daemons/gptp/common/avbts_clock.hpp, daemons/gptp/common/avbts_message.hpp, daemons/gptp/common/avbts_oscondition.hpp, daemons/gptp/common/avbts_osipc.hpp, daemons/gptp/common/avbts_oslock.hpp, daemons/gptp/common/avbts_osnet.hpp, daemons/gptp/common/avbts_osthread.hpp, daemons/gptp/common/avbts_ostimer.hpp, daemons/gptp/common/avbts_ostimerq.hpp, daemons/gptp/common/avbts_persist.hpp, daemons/gptp/common/avbts_port.hpp, daemons/gptp/common/gptp_cfg.cpp, daemons/gptp/common/gptp_cfg.hpp, daemons/gptp/common/ieee1588.hpp, daemons/gptp/common/ipcdef.hpp, daemons/gptp/common/ptptypes.hpp, daemons/gptp/linux/src/linux_hal_common.hpp, daemons/gptp/linux/src/linux_hal_generic.hpp, daemons/gptp/linux/src/linux_hal_generic_tsprivate.hpp, daemons/gptp/linux/src/linux_hal_intelce.hpp, daemons/gptp/windows/daemon_cl/IPCListener.hpp, daemons/gptp/windows/daemon_cl/Lockable.hpp, daemons/gptp/windows/daemon_cl/PeerList.hpp, daemons/gptp/windows/daemon_cl/Stoppable.hpp, daemons/gptp/windows/daemon_cl/packet.hpp, daemons/gptp/windows/daemon_cl/platform.hpp, daemons/gptp/windows/daemon_cl/windows_hal.hpp, daemons/gptp/windows/daemon_cl/windows_ipc.hpp
As promised in the automotive profile pull request review, I've put together a patch that fixes all the Doxygen-style comments that didn't have any tags at all. They now all have at least a @brief tag. There were just a couple that got a slight bit of extra rewording, but this is mostly a mechanical change.
There are also two or three places where I fixed the whitespace in close proximity to one of these comment blocks.
I found there was a common theme: C++ constructors and destructors almost universally had Doxygen-style comment blocks with no @brief or other tags. If this was intentional, maybe a better fix for those would be to turn them into regular comments instead of Doxygen comments with @brief? The Doxygen output with this patch in place doesn't look objectionable to me, although …
=> Change all doxygen-style comments to have a @brief

daemons/gptp/common/ieee1588port.cpp
The else clause was attached to the wrong if condition; as a result, sending of PDelay messages only worked when the automotive profile was enabled. Without PDelay transactions, the peer would never be asCapable and the rest of the protocol would never run.
I have verified that it does send PDelay requests when this patch is applied.
=> Fix logic for starting PDelay sending

daemons/gptp/common/ieee1588port.cpp
The automotive profile code merge introduced configuration parameters for the various interval timers, but unfortunately it set the initial Pdelay Request timer default incorrectly.  This patch fixes the problem.
=> Fix default initialLogPdelayReqInterval

daemons/gptp/common/ptp_message.cpp, daemons/gptp/linux/src/daemon_cl.cpp
The first patch fixes memory leak that occurs when receive unexpected message in PTP packet.
In addition,  checking transportSpecifit needs to be done after calling getRxTimestamp().
If buildPTPMessage() is returned before calling getRxTimeStamp() rxTimestampList will keep increasing in LinuxTimestamperGeneric class.
The second patch removes to assign duplicated InterfaceName object unnecessarily.
And this also occurs memory leak.
=> Memory leak

lib/avtp_pipeline/platform/Linux/openavb_time_osal.c
The version of gptpscaling in the new centralized avb library is just a wrapper around gptpgetdata with some printfs; the avtp_pipeline library doesn't need the printfs, so I have changed it to use gptpgetdata instead.
=> Change gptpscaling calls to gptpgetdata to avoid printfs

kmod/igb/igb.h, kmod/igb/igb_main.c
Prevent NULL pointer dereference at (null).
Kernel oops for put_page can be occurred by mutated application.
kernel: [ 2591.077666] BUG: unable to handle kernel NULL pointer dereference at           (null)
kernel: [ 2591.077672] IP: [<ffffffff81167625>] put_page+0x5/0x40
kernel: [ 2591.077674] PGD 7a3d16067 PUD 7ee0f4067 PMD 0 
kernel: [ 2591.077675] Oops: 0000 [#1] SMP
~~ snip ~~
kernel: [ 2591.077727]  ffff8807f07a74d8 ffff880035f4a480 ffff880798c73ee8 ffffffff811cce6d
kernel: [ 2591.077729]  ffff8807a3ca0210 ffff8807f2d88f20 0000000000000000 0000000000000000
kernel: [ 2591.077729] Call Trace:
kernel: [ 2591.077739]  [<ffffffffa067f631>] ? igb_close_file+0x81/0x170 [igb_avb]
kernel: [ 2591.077746]  [<ffffffff811cce6d>] __fput+0xbd/0x270
kernel: [ 2591.077748]  [<ffffffff811cd06e>] …
=> igb_avb: add mutex lock for memory alloc/free for userpage.

kmod/igb/igb_main.c
This change prevents from receiving kernel warnings ("map pfn RAM range req uncached-minus for[...]"). It is unecessary to call that method within igb_mmap(). The behaviour of the code after that change has been tested and proved to be working (no more kernel warnings and audio playback possible)
=> Removing redundant line causing AVB streamhandler writeback error

daemons/gptp/common/ap_message.cpp, daemons/gptp/common/avbts_clock.hpp, daemons/gptp/common/avbts_port.hpp, daemons/gptp/common/ieee1588clock.cpp, daemons/gptp/common/ieee1588port.cpp, daemons/gptp/common/ptp_message.cpp
Here is another set of fixes and improvements for gPTP with the focus on the automotive profile. See the list of commits for more information about what is changed.
=> gPTP Fixes and Improvements

Makefile, examples/simple_rx/Makefile, examples/simple_rx/README, examples/simple_rx/simple_rx.c, kmod/igb/igb.h, kmod/igb/igb_main.c, kmod/igb/igb_ptp.c, kmod/igb/kcompat.h, lib/igb/e1000_defines.h, lib/igb/e1000_osdep.h, lib/igb/igb.c, lib/igb/igb.h, lib/igb/igb_internal.h
This patch set adds support for direct packet receiving from the I210 device. The simple_rx application demonstrates how to use the new receive APIs. It was created based on simple_listener and it has the same usage. 
Signed-off-by: Toshiki Nishioka <toshiki.nishioka@intel.com>
=> add direct DMA for RX and misc fixes

examples/simple_rx/Makefile
Travis is still running ancient Ubuntu systems as their default build image. In pre-2.17 versions of GLIBC, -lrt is required to use `clock_gettime`, and it doesn't seem to cause a problem in post-2.17 versions.
=> Add -lrt to simple_rx build for Travis

daemons/gptp/linux/build/Makefile
Change in daemon/gptp/linux/build/Makefile which prevents the gPTP daemon build from failing (no more "igb.h undefined" error due to proper CPPFLAGS setting, ARCH=I210 make daemons_all ends with a success) - resolution to issues #390 and #385
=> Fixing issue #390 - gPTP daemon build failure with ARCH set to I210

kmod/igb/igb.h, kmod/igb/igb_main.c
Buffers must be released by task that requested mapbuf ioctl.
It prevents kernel oops due to incorrect memory free.
- add igb_private_data struct.
- move userpage list from igb_adapter to igb_private_data struct.
- separate igb_mapbuf_user from igb_mapbuf due to error cover code.
kernel oops is occurred in below case.
This patch prevents kernel oops for this problem.
1.process A
call igb_attach()
--> bind success
call igb_attach_tx()
--> TX ring buffer allocation success.
call igb_dma_malloc_page() seven times.
--> userpages allocation success.
waiting..
2.process B
call igb_attach()
call igb_attach_tx()
--> Error because TX ring buffer was already allocated by "process A".
call igb_deatch()
--> igb_close_file() function will be called by close() operation.
--> Problem is all buffers that …
=> igb_avb: move userpage list to private data of task.

daemons/gptp/common/avbts_message.hpp, daemons/gptp/common/ieee1588port.cpp
Starting with Wireshark 2.0.5 the signaling message in gPTP is reported as Malformed due to an incorrect value for the LengthField.
As defined in 802.1AS 2011 section 10.5.4.3.3 LengthField the length value shall be 12.
Currently gPTP is sending an incorrect value of 28.
Additionally for the signaling message TLV: 
Organization Subtype is 0x1 in the packet but it should be 0x2
LinkDelayInterval is 0x0 but for the Automotive Profile should be 127
Flags field is 0x0 in the packet but should be 0x3
=> Fixes to gPTP signaling message TLV values

daemons/gptp/common/ieee1588clock.cpp, daemons/gptp/common/ieee1588port.cpp
This pull request adds some NULL pointer checking related to announce processing.
=> gPTP - add some NULL  pointer checking

daemons/gptp/common/avbts_port.hpp, daemons/gptp/common/ieee1588.hpp, daemons/gptp/common/ieee1588port.cpp, daemons/gptp/linux/src/linux_hal_generic.cpp, daemons/gptp/linux/src/linux_hal_generic.hpp
As per issue #436 there are some problems with the way we were calling `timestamper_init` when we received link up events. That function is only designed to be called once, and causes resource leaks when called multiple times.
These patches create a 'reset' interface to the timestamper and call that instead on link up events. For the moment, it only resets the frequency adjustment, but if there are other useful things that need to happen when the link is restored we'll have a safe place to add them.
=> Change link up handling of hardware timestamper

kmod/igb/igb_main.c
Previous allocation was for the size of a pointer, not the structure.
This caused kernel memory corruption when the igb_avb driver was used
for streaming.
This should fix issue #474
=> igb: Fix alloc size for igb_private_data

Makefile, daemons/gptp/linux/build/Makefile, daemons/gptp/linux/src/daemon_cl.cpp, daemons/gptp/linux/src/linux_hal_common.cpp, daemons/gptp/linux/src/linux_hal_generic.cpp, daemons/gptp/linux/src/linux_hal_persist_file.cpp, daemons/maap/common/maap_protocol.c, daemons/maap/linux/maap_linux.c, daemons/mrpd/msrp.c, daemons/mrpd/msrp.h, examples/live_stream/listener.c, examples/simple_rx/Makefile, lib/igb/Makefile
Since added simple_rx, the clean target does not properly clean all the generated object and executable files. The changes here corrected the corresponding Makefiles to be able to remove all the generated files.
Besides that, when added -O2 to Open AVB daemons Makefile CFLAGS, there are some compile warnings and errors shown. The changes here also fix those warnings and errors.
This should fix #473 too.
Regards,
Roland Hii
=> Fixes to Makefiles and compiler warnings and errors

.travis.yml, CMakeLists.txt, daemons/mrpd/tests/simple/parse_tests.cpp
This is a fix for #448 
It enables C++11 support in the CppUTest build via a change to the top-level CMakeLists.txt file, and also fixes some warnings from our MRPD unit tests that showed up as a result of the change.
=> Enable C++11 support in CppUTest

daemons/gptp/common/avbts_port.hpp, daemons/gptp/common/ieee1588port.cpp, daemons/gptp/linux/src/daemon_cl.cpp, daemons/gptp/windows/daemon_cl/daemon_cl.cpp
Completely remove accelerated sync on gPTP daemon startup. I think I have covered everything - comments welcomed.
=> gPTP: remove accelerated SYNC send on startup. See discussion in #465.

daemons/mrpd/msrp.c
Note: This memory leak only occurs if TalkerAdv stream pruning is active
(cmdline option -p). Attributes that were selected to be pruned during
event processing were not being free'd.
=> MRP: BUGFIX - memory leak in MSRP when checking for interesting streams

daemons/gptp/linux/src/linux_hal_common.cpp
This pull request fixes an issue that the link up and down detection in gPTP was not checking if the interface with the link event was the interface in use by gPTP. This would result in gPTP acting on incorrect link events on systems with multiple network interfaces. This issue was in Linux specific code.
Requesting expedited review of this pull request due to it blocking a customer release.
=> Fix gPTP link up/down detection. Check only the interface used by port

daemons/gptp/linux/src/daemon_cl.cpp, daemons/gptp/linux/src/linux_hal_generic.cpp, daemons/gptp/linux/src/linux_hal_i210.cpp, daemons/gptp/linux/src/linux_hal_persist_file.cpp
Solution proposal to issue #490 which is linked with printf calls within the gptp code.
Please note that this is supposed to serve as an introductory/first commit for a new member of Automotive society within Intel Technology Poland (Piotr Sowiński).
=> Fix proposal to the issue 490

daemons/gptp/common/ieee1588.hpp, daemons/gptp/common/ptptypes.hpp, daemons/gptp/linux/shm_test/shm_test.cpp, kmod/igb/Makefile, lib/igb/igb.c
Add SUPPORT_32BIT_IOCTL to CCFLAGS to support 32 bit ioctl system call
=> Support 32/64 bits build

lib/avtp_pipeline/qmgr/openavb_qmgr.c
Added small margin +1 to packet size in qmgr.
See issue #492.
=> AVTP pipeline: fixed bandwitdh reservation.

daemons/gptp/linux/build/Makefile
Fixing gptp Makefile - precise time test using CC variable instead of…gcc all the time
=> FIxing gptp Makefile - precise time test using CC 

daemons/gptp/common/ptp_message.cpp
correctionField doesn't need to be shifted again when logging as
it's done a few lines above.
=> gptp: fix wrong Follow_up Correction Field value in GPTP_LOG_VERBOSE

examples/simple_rx/simple_rx.c, lib/igb/igb.c
- alignment correction for the flex filter length
- sanity checks for the ring buf registers
The FHFT.Length filed must have a 8 bytes aligned value according to the I210 datasheet. Otherwise it could cause unexpected behaviors. Indeed simple_rx had a problem that it consumed all VLAN tagged received packets even if they were not AVB packets.
=> libigb: add alignment checks for register values

README.rst
It has been saying 'build unknown' because it's pointed at the AVnu/Open-AVB URL, which is no longer active on Travis. This points it at Avnu/OpenAvnu, which is active and shows the correct build status badge.
Also, changed one last "AVB" to "AVB/TSN".
=> Fix Travis build status URL in README

daemons/gptp/common/avbts_port.hpp, daemons/gptp/common/ieee1588port.cpp, daemons/gptp/linux/src/daemon_cl.cpp, daemons/gptp/linux/src/linux_hal_common.cpp
Mulitple LINKUP events are observed during interface manipulations
(e.g. adding or removing VLANs), so this change checks when
the ifi_flags gets IFF_RUNNING bit changed.
=> gPTP: redundant (false) LINKUP events filtering

kmod/igb/igb_main.c
1. commit be07cb5
Fixing dma memory corruption during suspend - during S3 test there was a discovery of a memory corruption resulting in kernel panic. That was caused by memory beeing freed within suspend function. Keeping the memory in driver suspend prevents from the uexpected fatal behaviour
2. commit 7265634
Checking Tx and Rx queues number in igb_mapbuf - change due to kernel NULL pointer dereference in reboot test. There is a possibility that user space calls igb_ioctl_fila -> igb_mapbuf after the ring has been reset (and the tx/rx_rings have been NULL'ed). Therefore the patch check if tx and rx queues numbers are cleared to zero before accessing adapters tx_ring and rx_ring in igb_mapbuf
=> S3 test and reboot test fixes - memory corruption/NULL ptr dereference

daemons/gptp/README_SYSTEMD_WATCHDOG.txt, daemons/gptp/linux/build/Makefile, daemons/gptp/linux/src/daemon_cl.cpp, daemons/gptp/linux/src/linux_hal_common.cpp, daemons/gptp/linux/src/watchdog.cpp, daemons/gptp/linux/src/watchdog.hpp
This is code adds systemd watchdog notifications to gPTP daemon.
The solution reads WatchdogSec parameter from service configuration file and notifies watchdog
every 0.5*WatchdogSec that gPTP daemon is alive.
If there is no watchdog configuration available or WatchdogSec == 0, watchdog notification won't run.
Watchdog configuration is read once during gPTP daemon startup.
=> Systemd watchdog

daemons/maap/common/maap_log_queue.c, daemons/maap/common/maap_parse.c, daemons/maap/test/maap_log_dummy.c, daemons/maap/windows/src/maap_log_windows.c
Updates to allow Microsoft Visual Studio 2012 (and perhaps earlier versions) to compile the CppUTest test cases.
=> Added support  for Microsoft Visual Studio 2012

daemons/maap/common/maap.c, daemons/maap/common/maap.h, daemons/maap/common/maap_iface.h, daemons/maap/common/maap_parse.c, daemons/maap/common/maap_parse.h, daemons/maap/linux/src/maap_daemon.c
Restructured the MAAP daemon to make the code more generic.
Clients that want to interact with the MAAP daemon using text (such as telnet clients) are now supported.
Added prompt to tell the user to type "help" for commands.
Fixed an issue when receiving multiple binary notifications.
Fixed some memory leaks with invalid command-line flags.
=> MAAP daemon updates

daemons/gptp/CMakeLists.txt, daemons/gptp/common/ptp_message.cpp, daemons/gptp/windows/daemon_cl/gptp.manifest
Added a manifest indicating Windows 10 support to the Windows gPTP build, so that Windows 10 detection will work correctly.  Manifest support is available with CMake 3.4 and later.
Also changed ptp_message.cpp to address a x64 compile warning.
Note that these changes were only tested with Microsoft Visual Studio Premium 2012 Update 5, and not with any other compilers.
=> Windows 10 detection fix

daemons/maap/common/maap.c, daemons/maap/common/maap.h, daemons/maap/common/maap_iface.h, daemons/maap/common/maap_parse.c, daemons/maap/linux/src/maap_daemon.c
This update provides an easy way to test the "yield" behavior of daemon clients.  This state occurs when a MAAP DEFEND PDU is received by the MAAP daemon from a device with a lower MAC Address that conflicts with a multicast address being defended by the daemon.  When the conflict occurs (either by receiving an applicable MAAP DEFEND PDU, or by using the "yield" command), the daemon client with the conflicting reservation will receive a MAAP_NOTIFY_YIELDED notification, followed by MAAP_NOTIFY_ACQUIRING and MAAP_NOTIFY_ACQUIRED notifications for the newly reserved MAAP multicast address.
=> Added YIELD command support to the MAAP daemon

daemons/gptp/common/avbts_clock.hpp, daemons/gptp/common/avbts_message.hpp, daemons/gptp/common/avbts_osipc.hpp, daemons/gptp/common/ieee1588.hpp, daemons/gptp/common/ieee1588clock.cpp, daemons/gptp/common/ipcdef.hpp, daemons/gptp/common/ptptypes.hpp, daemons/gptp/linux/shm_test/shm_test.cpp, daemons/gptp/linux/src/linux_hal_common.cpp, daemons/gptp/linux/src/linux_hal_common.hpp, daemons/gptp/windows/daemon_cl/IPCListener.hpp, daemons/gptp/windows/daemon_cl/windows_hal.cpp, daemons/gptp/windows/daemon_cl/windows_hal.hpp, daemons/gptp/windows/daemon_cl/windows_ipc.hpp
Added information used by AVDECC to the gPTP daemon shared memory.
Also standardized references to IEEE 802.1AS-2011 in the comments.
=> Added AVDECC information to gPTP daemon

daemons/gptp/common/ptp_message.cpp
As the twoStepFlag value is not used, and should be ignored, added a change to not test that the flag is set.
This allows the gPTP daemon to work with switches, such as MOTU, that do not set this flag.
=> Ignore twoStepFlag as per Table 11-4 of 802.1AS-2011

daemons/gptp/common/avbts_clock.hpp, daemons/gptp/common/ieee1588clock.cpp, daemons/gptp/common/ptp_message.cpp
This change checks if time in follow_up messages is monotonic
and will discard “wrong” sync/follow_up to prevent calculating
incorrect values (ratio etc.). It was observed for some bridges
and for some cases, that such situation might happens (bridge issue)
and could lead to huge time instability, especially when syntonization
functionality is activated.
=> gPTP: add negative time jumps detection

lib/igb/igb.c, lib/igb/igb_internal.h
libigb used a posix named semaphore to protect concurrent accesses from
multiple processes. But since the posix semaphore cannot be automatically
released on process termination, if some process holding the semaphore
terminates without releasing it, other processes cannot acquire the semaphore
afterward. This could potentially cause a denial of service condition.
This patch replaces the posix named semaphore by a posix mutex.
In addition this patch adds a flag which prevents access to device after
calling igb_detach. Since igb_detach frees up associated resources, other
thread in multi-thread application should not access device once some thread
started resource clean-up by calling igb_detach. Otherwise invalid access to
freed memories could happen.
=> libigb: improve inter-process synchronization

daemons/gptp/common/ether_port.cpp, daemons/gptp/common/ieee1588clock.cpp, daemons/gptp/linux/src/linux_hal_generic.cpp, daemons/gptp/linux/src/linux_hal_generic.hpp, daemons/gptp/linux/src/linux_hal_generic_adj.cpp
Proper HWTimestamper_adjclockrate was not executed due to
const-overloading issue and "Failed to adjust clock rate"
error was flooding (broken syntonization). Additional fix
for compilation error ('sync_timestamp' not declared) when
verbosity logs are activated.
=> gPTP: change HWTimestamper_adjclockrate into const function

daemons/gptp/linux/src/linux_hal_common.cpp
Use an INET socket rather than a NETLINK socket to get link speed
with ioctl() since NETLINK sockets do not support ioctl().
=> gPTP: fix SIOCGIFNAME ioctl failure

lib/igb/igb.c
Also, removed some trailing spaces.
Signed-off-by: David Cemin <david.cemin@coveloz.com>
=> libigb: Fix some compiler warnings

lib/avtp_pipeline/README.md, lib/avtp_pipeline/documents/sdk_avtp_interface_module_dev.md, lib/avtp_pipeline/documents/sdk_avtp_stream_cfg.md, lib/avtp_pipeline/documents/sdk_eavb_integration.md, lib/avtp_pipeline/documents/sdk_notes_media_queue_usage.md, lib/avtp_pipeline/documents/sdk_overview.md, lib/avtp_pipeline/intf_tonegen/openavb_intf_tonegen.md, lib/avtp_pipeline/platform/Linux/intf_alsa/alsa_intf.md
Added AVDECC and MAAP references to README.md
Added additional parameters to oopenavb_intf_tonegen.md and alsa_intf.md
General formatting changes so that headers and tables will display correctly on GitHub
=> AVTP Pipeline Documentation Updates

daemons/gptp/common/common_port.hpp
PortInit_t used char fields to store signed sentinel values to
indicate that default values should be set by the port. This was
fine for Intel, which generally has a signed representation for
the char type, but the sentinel values were not recognized on ARM
platforms, where char is generally unsigned.
Changing the fields to explicitly be of signed char type resolves
the problem on ARM and keeps the same behavior on Intel.
=> Fix for gPTP interval init on ARM platforms

daemons/gptp/common/common_port.hpp, daemons/gptp/common/ether_port.hpp
The previous fix correctly identified the problem but was incomplete--this
one has actually been verified to work. More `char` fields had to be changed
to `signed char` to avoid problems with negative numbers.
=> Rest of fix for gPTP intervals on ARM

daemons/gptp/common/common_port.cpp, daemons/gptp/common/common_port.hpp, daemons/gptp/common/ether_port.hpp, daemons/mrpd/mrpctl.c, daemons/shaper/src/shaper_daemon.c, lib/avtp_pipeline/endpoint/openavb_endpoint.c, lib/avtp_pipeline/maap/openavb_maap.h, lib/avtp_pipeline/platform/Linux/endpoint/openavb_endpoint_cfg.c, lib/avtp_pipeline/platform/Linux/endpoint/openavb_endpoint_cfg.h, lib/avtp_pipeline/platform/Linux/endpoint/openavb_endpoint_osal.c, lib/avtp_pipeline/platform/Linux/endpoint/openavb_endpoint_osal_maap.c, lib/avtp_pipeline/platform/Linux/tl/openavb_tl_osal.c, lib/avtp_pipeline/tl/openavb_tl.c
Thread priority and affinity supported for Listeners
Added initial support to save useful information to the endpoint_save.ini file for re-use the next time the application is run.  By design, the ini file is only updated as needed.  Currently saving the assigned MAAP address so that the same address can be requested again.
If the shaper daemon receives a Ctrl-C signal, it shuts down as if the user called the quit ("-q") command, rather than just aborting.  This allows for cleanup of the current configuration to occur.
White space fixes.
=> MAAP addresses reused, shaper daemon shutdown fix

lib/avtp_pipeline/map_aaf_audio/openavb_map_aaf_audio.c, lib/avtp_pipeline/map_aaf_audio/openavb_map_aaf_audio_pub.h, lib/avtp_pipeline/map_uncmp_audio/openavb_map_uncmp_audio.c, lib/avtp_pipeline/map_uncmp_audio/openavb_map_uncmp_audio_pub.h, lib/avtp_pipeline/map_uncmp_audio/uncmp_audio_map.md, lib/avtp_pipeline/platform/Linux/intf_alsa/aaf_file_talker.ini, lib/avtp_pipeline/platform/Linux/intf_alsa/aaf_listener.ini, lib/avtp_pipeline/platform/Linux/intf_alsa/aaf_listener_auto.ini, lib/avtp_pipeline/platform/Linux/intf_alsa/aaf_talker.ini, lib/avtp_pipeline/platform/Linux/intf_alsa/openavb_intf_alsa.c, lib/avtp_pipeline/platform/Linux/intf_wav_file/openavb_intf_wav_file.c
Changes to the AAF support to make it compatible with IEEE 1722-2016 Clause 7.
Listener will adjust to use the sparse mode and integer size of the Talker.
Talker sparse mode support moved from intf (ALSA and WAV) to map_aaf.
=> AAF Updates

daemons/gptp/common/common_port.cpp
The change is required to prevent a deadlock that occurs
when PTPMessageSignalling is received in the middle of
processEvent SYNC_INTERVAL_TIMEOUT_EXPIRES
Signed-off-by: Michal Wasko <michal.wasko@intel.com>
=> SyncIntervalTimer lock changed to trylock

daemons/gptp/common/ether_port.cpp
PTP Master/Slave port role restore added to
Link Up event processing to guarantee proper
gPTP daemon re-sync after Link loss situation
due to partner platform reboot. The PTP role
restore is especially important for the case
when platforms are connected directly with
ethernet cable - no switch in between.
Signed-off-by: Michal Wasko <michal.wasko@intel.com>
=> PTP Port role restore on Link Up event

daemons/gptp/common/common_port.cpp
The change fix a problem of gPTP daemon synchronization
in non-automotive profile when daemon is  not ready at
start (asCapable=false) - for example due to link down.
In above situation with previous implementation the
announce interval timer will not restart on
ANNOUNCE_INTERVAL_TIMEOUT_EXPIRES event.
Signed-off-by: Michal Wasko <michal.wasko@intel.com>
=> gPTP Announce interval timer restart fixed

daemons/gptp/common/common_port.cpp, daemons/gptp/common/ether_port.cpp
Currently, if starting two instances of daemon_cl, they do not connect to each other because neither listens for announce messages. This changes them from sending announces to listening. They then start announcing after an ANNOUNCE_RECEIPT_TIMEOUT_EXPIRES event.
=> listen for announces on init and linkup

lib/avtp_pipeline/include/openavb_audio_pub.h, lib/avtp_pipeline/map_aaf_audio/openavb_map_aaf_audio.c
Added the missing 24 kHz rate to the list of supported rates.  (See  IEEE 1722-2016 Table 11)
Fix for case where audio payload is from two different media queue items (just in case).
Trace fix to use AVB_TRACE_MAP rather than AVB_TRACE_INTF.
=> AAF 24 kHz support, cleanup

lib/avtp_pipeline/endpoint/openavb_endpoint_server.c, lib/avtp_pipeline/platform/Linux/avdecc/openavb_avdecc_cfg.c, lib/avtp_pipeline/platform/Linux/endpoint/openavb_endpoint_cfg.c, lib/avtp_pipeline/platform/Linux/rawsock/simple_rawsock.c, lib/avtp_pipeline/platform/Linux/tl/openavb_tl_osal.c, lib/avtp_pipeline/qmgr/openavb_qmgr.c, lib/avtp_pipeline/tl/openavb_listener_endpoint.c, lib/avtp_pipeline/tl/openavb_listener_no_endpoint.c, lib/avtp_pipeline/tl/openavb_talker_endpoint.c, lib/avtp_pipeline/tl/openavb_talker_no_endpoint.c, lib/avtp_pipeline/tl/openavb_tl_pub.h
More updates so that network interfaces include length for the rawsock type
prefix, and so the strncpy() commands use the extra length.
Also includes removal of some trailing whitespace.
=> Network interface string length consistency

lib/avtp_pipeline/map_aaf_audio/openavb_map_aaf_audio.c
Update to return more appropriate frame sizes based on Talker or Listener role.
=> AAF returns appropriate max frame size for Talkers vs Listeners

lib/avtp_pipeline/platform/Linux/avb_avdecc/openavb_avdecc.c, lib/avtp_pipeline/platform/Linux/avb_host/openavb_harness.c, lib/avtp_pipeline/platform/Linux/avb_host/openavb_host.c, lib/avtp_pipeline/platform/Linux/openavb_osal.c, lib/avtp_pipeline/platform/Linux/openavb_osal_avdecc.c, lib/avtp_pipeline/platform/Linux/openavb_osal_endpoint.c, lib/avtp_pipeline/platform/Linux/openavb_osal_pub.h
AVTP Pipeline (openavb_host and openavb_harness) and AVDECC (openavb_avdecc)
have a new "-l" option to specify the filename of the log file to use.  If not
specified, then the behavior is unchanged, and stderr is used for logging.
=> Added logging support

daemons/gptp/linux/src/linux_hal_common.hpp, daemons/gptp/linux/src/linux_hal_generic_adj.cpp
Eventually the additional #define can be removed, this is fixed in recent header files. I'm not sure if there are older header files that are even more broken that we want to support(?) I don't have very many installs to test against.
=> RFC: Simplify timeval & timespec redefinition fix

README.rst
Per your request, I've altered the main readme with linking information to the fork containing the apple vendor ptp profile changes.
=> Add a note to the readme for the aPTP change fork.

run_daemons.sh, stop_daemons.sh
Added shaper_daemon to run_daemons.sh and stop_daemons.sh.
Fixed the path and parameters for maap_daemon.
IGB is now initialized separately, as the daemons can be run without it.
Don't assume the name of the NIC, and don't include "sudo" in the script, to
be consistent with the other run_*.sh scripts.
=> Daemon scripts cleanup

daemons/gptp/common/ptptypes.hpp, daemons/gptp/linux/src/linux_hal_generic.cpp
It fixes daemon_cl behavior in the following situation.
1. Sent gPTP message.
2. Try to get the timestamp.
3. Repeat no. 2 until timeout occurs.
4. Timeout occurs, continue operation.
5. Timestamp comes (but it's not read).
6. Sent another gPTP message.
7. Try to get the timestamp.
8. Read the timestamp -> Timestamp from message no. 1 is being read.
9. Time synchronization fails due to the wrong Tx timestamp.
This fix discards stale Tx timestamps. It checks message type and sequence id of the reflected packet to see if it contains the timestamp for the frame being sent at the moment. In case it doesn't the timestamp is discarded.
=> Fixing stale Tx timestamp fetch.

lib/avtp_pipeline/README.md, lib/avtp_pipeline/platform/Linux/intf_alsa/example_listener.ini, lib/avtp_pipeline/platform/Linux/intf_alsa/example_talker.ini, run_avtp_pipeline.sh, stop_avtp_pipeline.sh
Added example Talker and Listener .ini files.
Added scripts to start and stop the AVTP Pipeline as a Talker & Listener.
README updates describing how to use the updated scripts and .ini files.
=> Added AVTP Pipeline Example

daemons/gptp/README.rst, daemons/gptp/common/avbts_clock.hpp, daemons/gptp/common/avbts_message.hpp, daemons/gptp/common/avbts_osipc.hpp, daemons/gptp/common/common_port.cpp, daemons/gptp/common/common_port.hpp, daemons/gptp/common/ether_port.cpp, daemons/gptp/common/ether_port.hpp, daemons/gptp/common/ieee1588.hpp, daemons/gptp/common/ptp_message.cpp, daemons/gptp/common/wireless_port.cpp, daemons/gptp/common/wireless_port.hpp, daemons/gptp/common/wireless_tstamper.cpp, daemons/gptp/common/wireless_tstamper.hpp, daemons/gptp/linux/src/daemon_cl.cpp, daemons/gptp/windows/daemon_cl/daemon_cl.cpp, daemons/gptp/windows/daemon_cl/intel_wireless.cpp, daemons/gptp/windows/daemon_cl/intel_wireless.hpp, daemons/gptp/windows/daemon_cl/tsc.hpp, daemons/gptp/windows/daemon_cl/windows_hal.cpp, daemons/gptp/windows/daemon_cl/windows_hal.hpp, daemons/gptp/windows/daemon_cl/work_queue.cpp, daemons/gptp/windows/daemon_cl/work_queue.hpp, daemons/gptp/windows/named_pipe_test/named_pipe_test.cpp
buildPTPMessage friend declarations and function definition now use
CommonPort object
processMessage method in PTP message classes now use CommonPort argument
redundant documentation for buildPTPMessage and processMessage removed
leaving only that in the base class
Add cast to addEventTimerLocked() call (CommonPort::processEvent)
preventing Windows compiler warnings
Moved all message interval maintenance to CommonPort, also simiplifying
Signal message processing
Divided FollowUp processing code into two functions for code received on
an EtherPort or a WirelessPort (as a Vendor Extension)
Modified Windows daemon code to accept a wireless flags
Added Windows wireless adapter abstract class to implement a PROSet-like
interface for Windows
Implemented an Intel specific Windows wireless …
=> Added wireless timestamper and port code

daemons/gptp/common/ether_port.cpp
Trigger initial PDelay calculation without waiting full interval (def. 1 sec).
For Automotive Profile and fast initial Sync rate, we are losing that 1 sec.
due to discarded (not processed) Follow_up messages (delay = INVALID_LINKDELAY).
=> Start PDelay calculation as fast as possible in Automotive Profile

daemons/gptp/linux/src/linux_hal_common.cpp
It was sometimes (2/100 + high cpu load) observed that signal thread
was not started (timerq->stop), which led to missing initial PDelay calculation and
thus to no Sync/Follow_up processing. Plus some debug logs added.
=> gptp: fix race condition during signal thread creation

.travis.yml, travis.sh
This patch hooks libavtp into travis in order to have the CI system
building libavtp and example applications, as well as running the unit
tests.
Libavtp dependencies are installed manually because the packages
provided by Ubuntu Trusty are very old versions and incompatible. Also,
likewise ethtool.h and ptp_clock.h, this patch copies the if_ether.h
header from linux-headers-4.4.0-75 directory to /usr/include since the
version provided by Trusty is very old and doesn't define the ETH_P_TSN
macro.
Finally, this patch sets CFLAGS=-Wno-missing-braces when building
libavtp in order to silent a warning generated by gcc. Travis is using a
very old gcc version (4.8) which wrongly warns about universal zero
initializer (more details about this on …
=> travis: Hook in libavtp

lib/libavtp/meson.build
This patch adds support for pkg-config in order to make it easier to
other projects to link against libavtp.
We leverage Meson builtin support for generating and installing the
.pc file.
=> libavtp: Add pkg-config support

kmod/igb/igb.h, kmod/igb/igb_main.c
Adding support for newer kernel versions and ensuring backward compatibility. Changes include:
a) support for removing vm_area_struct argument from kernel sources in versions 4.11.0 and higher
b) removal of pci_enable_msix method in kernel sources 4.12.0 or higher
c) including miscdevice.h so that the driver recognizes igb_miscdevice elements
This change resolves the problem of igb_avb driver causing compilation error in kernel versions higher than 4.10. It has been tested with several kernel versions (ranging from 4.4 till 4.14) in order to make sure that it does not introduce any regression.
=> Kernel update support

kmod/igb/e1000_osdep.h, kmod/igb/igb_main.c
This PR makes changes necessary to build the IGB_AVB kernel driver with Linux v4.16-rc4 (and hopefully 4.16, when it is released).
Changes:
- `ACCESS_ONCE` is no longer available, replaced with `READ_ONCE`
- `setup_timer` is no longer available, replaced with `timer_setup`
=> Port IGB_AVB to Linux v4.16-rc4

kmod/igb/e1000_82575.c, kmod/igb/igb.h, kmod/igb/igb_ethtool.c, kmod/igb/igb_main.c, kmod/igb/igb_param.c
Recently Klocwork tool has been applied to the igb_avb driver code and as a consequence I'm pushing some resolved issues reported by that tool:
a) e1000_82575.c : e1000_clock_in_i2c_byte always returns "0" and other methods from the i2c API called within this method do the same. Therefore there is no sense in checking whether the returned value is !0 as it will never happen
b) igb_ethtool.c : 
1. changing phy.type into phy.id as it was compared with the wrong define value
2. igb_setup_loopback_test returns always 0 so there is no point I checking the output. The if   statement applied to igb_run loopback_test instead (more meaningful)
3. Retrieve "*" operator not needed in case of memcpy and passing table igb_gstrings_test address
c) igb_main.c : igb_up returns always 0, so if(igb_up) …
=> Resolving Klocwork Static Code Analysis issues

.travis.yml
Meson 0.45 was released recently and it requires Python 3.5 which is not
installed in travis environment. This patch changes .travis.yml so
version 0.44 is installed instead.
=> travis: Stick to meson version 0.44

lib/avtp_pipeline/map_h264/openavb_map_h264.c, lib/avtp_pipeline/map_h264/openavb_map_h264_pub.h, lib/avtp_pipeline/platform/Linux/gst_al/gst_al.h, lib/avtp_pipeline/platform/Linux/gst_al/gst_al_10.c, lib/avtp_pipeline/platform/Linux/intf_h264_gst/openavb_intf_h264_gst.c
This commit adds support for H.264 video timestamp for talker and listener interface using GStreamer.
For details refer to IEEE 1722-2016 8.5.3.1 h264_timestamp field.
=> Adding h264 timestamp field to AVTP h264 video header and fixed typo

daemons/gptp/common/ptp_message.cpp
A object of pdelay_req is managed(create&delete) at ethe_port.
but it also could be deleted at a step for processing of pdelay_resp.
Thus, there is a race condition.
Those sequence should be deleted for some reasons below:
1. If pdelay_req is trigged in the middle of processing pdelay_resp, then 'null point exception' could be happened.
2. The available pdelay_req would(should) be kept until sending next pdelay_req. Becuase it is possible to receive correct pdelay_resp even after unexpected error at processing pdelay_rest.
=> gptp : remove unnecessary sequence that try to delete pdelay request object.

daemons/gptp/common/ptp_message.cpp
PDelayRequest seqId was used as PDelayRespFollowUp seqId.
=> Wrong seqId used in log message

daemons/gptp/common/avbts_clock.hpp, daemons/gptp/common/common_port.cpp
This is to fix issue #776 by adding timer queue lock in startSyncReceiptTimer and stopSyncReceiptTimer.
=> Fix the dead lock when handling SYNC_RECEIPT_TIMEOUT_EXPIRES event

daemons/gptp/common/common_tstamper.hpp, daemons/gptp/common/gptp_cfg.cpp, daemons/gptp/common/gptp_cfg.hpp, daemons/gptp/gptp_cfg.ini, daemons/gptp/linux/build/Makefile, daemons/gptp/linux/src/daemon_cl.cpp, daemons/gptp/linux/src/linux_hal_generic.cpp, daemons/gptp/linux/src/linux_hal_generic.hpp
Timestamp clocks that implement the PTP_SYS_OFFSET_PRECISE ioctl return
cross-timestamps with respect to monotonic raw and realtime
Add configuration file option allowing clock selection for system/local
clock relation
The default clock type is Realtime which is equivalent to the
CLOCK_REALTIME option to clock_gettime
Optionally, MonotonicRaw (equivalent to CLOCK_MONOTONIC_RAW) can be
specified in the gPTP daemon configuration file:
[clock]
SystemClock = MonotonicRaw
Fixed Makefile issue where some shell configurations use built-in 'echo'
and others don't
Forces all to use /bin/echo
=> gptp: Add monotonic raw clock option

lib/avtp_pipeline/map_aaf_audio/openavb_map_aaf_audio.c
OpenAvnu is great test tool for other AVB stacks. Sometimes on MCUs we have to use non-standard AAF format for performance reasons. Like when little-endian MCU have to handle 32 channels of 32 bit class A low latency audio. Byte swapping in software is just too much.
This fix will allow talkers to use little-endian settings.
=> Map AAF uses userspecific format for little endian

lib/avtp_pipeline/tl/openavb_talker.c, lib/avtp_pipeline/tl/openavb_tl.c, lib/avtp_pipeline/tl/openavb_tl_pub.h
Sometime ago spin wait was made separate from fixed_timestamp, this caused regression in builds using IGB_LAUNCHTIME_ENABLED=1.
This PR adds *launchtime* flag to talker which will be set automatically if IGB/ATL_LAUNCHTIME_ENABLED is used.
Otherwise we would need to use spin_wait flag to make launchtime work which would be counter-intuitive.
Both spin_wait and launchtime mode work on WALLCLOCK, but launchtime doesn't need any waiting because it will be done in ethernet driver.
So, we will have 3 modes for packet scheduling:
- sleep
- spin_wait
- launchtime
=> Added launchtime flag to talker

lib/avtp_pipeline/platform/Linux/avb_host/CMakeLists.txt, lib/avtp_pipeline/platform/Linux/avb_host/openavb_harness.c, lib/avtp_pipeline/tl/openavb_tl.c, lib/avtp_pipeline/tl/openavb_tl_pub.h
This will allow creating GUI for openavb_harness. 
Example use cases.
To change volume at runtime enter in openavb_harness:
c0 intf_nv_volume -20
To change filename of played wav file:
c1 intf_nv_file_name test2.wav
c0, c1 means stream 0, stream 1 respectively.
Of course, it is not particularly handy to enter whose commands manually, but you can write the GUI wrapper which runs the openavb_harness and then issues those commands in response to user actions.
=> Configuration options can be changed at runtime

README.rst
=> README.rst: fix code block annotation

daemons/maap/linux/src/maap_log_linux.c, daemons/shaper/src/shaper_log_linux.c, lib/avtp_pipeline/platform/Linux/openavb_tasks.h
Since [Glibc 2.34](https://lists.gnu.org/archive/html/info-gnu/2021-08/msg00001.html) PTHREAD_STACK_MIN isn't a constant anymore. This checks if _DYNAMIC_STACK_SIZE_SOURCE is defined and determines THREAD_STACK_SIZE in run-time.
=> Be compatible with dynamic stack size
