Avnu/OpenAvnu

- documents/design/AVnu_gPTP_Code.asciidoc
It seems to have carried over pretty well.  I only had to fix one section of markup.
Here's the link to the file in my fork of Open-AVB so you can see how it renders: https://github.com/pinealservo/Open-AVB/blob/open-avb-next/documents/design/AVnu_gPTP_Code.md
> Markdown translation of Chris's gPTP design document

- daemons/maap/common/maap_protocol.c
- daemons/maap/common/maap_protocol.h
- daemons/maap/linux/maap_linux.c
Signed-off-by: manjunathhadli <manjunath.hadli@vayavyalabs.com>
> changed the file licenses from GPL to BSD.

- daemons/gptp/common/avbts_port.hpp
simple addition of a single method
> gPTP: add method to retrieve asCapable from IEEE1588Port class.

- kmod/igb/igb_ptp.c
- kmod/igb/kcompat.h
> igb: fix build on 32-bit kernels

- lib/igb/igb.c
- lib/igb/igb.h
Couple of libigb fixes. Success returned on error from igb_attach_tx, missing locking in igb_clean.
> Open avb next

- lib/avtp_pipeline/map_h264/openavb_map_h264.c
- lib/avtp_pipeline/platform/Linux/avb_host/openavb_harness.c
- lib/avtp_pipeline/platform/Linux/avb_host/openavb_host.c
- lib/avtp_pipeline/platform/Linux/intf_h264_gst/openavb_intf_h264_gst.c
- lib/avtp_pipeline/platform/Linux/openavb_osal.c
- lib/avtp_pipeline/platform/Linux/openavb_osal_pub.h
- lib/avtp_pipeline/platform/Linux/tl/openavb_tl_osal.c
- lib/avtp_pipeline/platform/x86_i210/openavb_ether_hal.c
- lib/avtp_pipeline/platform/x86_i210/openavb_time_hal.c
- lib/avtp_pipeline/qmgr/openavb_qmgr.c
- lib/avtp_pipeline/util/openavb_log.c
- lib/igb/igb.c
- lib/igb/igb.h
openavb_host/harness, h264, logging improvements.
> Small improvements

- kmod/igb/igb_main.c
Function igb_add_rx_frag taken from before commit:
AVNu/Open-AVB/2fdb56a391e9e09ff22837e56d594507fbaf9250
> Fixes: #276 - Problems with receiving frames longer than 256 bytes.

- Makefile
- lib/avtp_pipeline/README.md
- lib/avtp_pipeline/avtp_pipeline.mk
- lib/avtp_pipeline/documents/Doxyfile.in
- lib/avtp_pipeline/documents/index.md
- lib/avtp_pipeline/documents/sdk_avtp_stream_cfg.md
- lib/avtp_pipeline/include/openavb_map_pub.h
- lib/avtp_pipeline/intf_tonegen/openavb_intf_tonegen.md
- lib/avtp_pipeline/intf_viewer/viewer_intf.md
- lib/avtp_pipeline/mediaq/openavb_mediaq_pub.h
- lib/avtp_pipeline/platform/Linux/intf_alsa/alsa_listener.ini
- lib/avtp_pipeline/platform/Linux/intf_mjpeg_gst/mjpeg_gst_listener.ini
- lib/avtp_pipeline/platform/Linux/intf_mjpeg_gst/mjpeg_gst_talker.ini
- lib/avtp_pipeline/platform/Linux/intf_mpeg2ts_gst/mpeg2ts_gst_listener.ini
- lib/avtp_pipeline/tl/openavb_tl_pub.h
- run_echo_listener.sh
Updated readme file for AVTP pipeline, updated API documentation and integrated into build process. Ini files improvements; added pipelines for gstreamer 1.0.
> AVTP pipeline documentation improvements

- documents/design/oavb_ipc.asciidoc
> documents: design: add avb_ipc.asciidoc draft

- documents/design/oavb_ipc.asciidoc
split in to sync and async sections
> Feature ipc doc

- documents/design/AVnu_gPTP_Code.asciidoc
This pull request links in images from gh-pages to the gPTP design doc.
> doc: gPTP add sequence diagrams

- kmod/igb/igb_main.c
- kmod/igb/kcompat.h
Fix builds on recent kernels.
Signed-off-by: Todd Fujinaka <todd.fujinaka@intel.com>
> igb-avb: fix builds on 3.19 kernels et al

- index.html
create link to AVTP pipeline web pages
> add AVTP pipeline documentation

- daemons/gptp/common/avbts_osnet.cpp
- daemons/gptp/common/avbts_osnet.hpp
- daemons/gptp/common/avbts_port.hpp
- daemons/gptp/common/ieee1588.hpp
- daemons/gptp/common/ieee1588port.cpp
- daemons/gptp/linux/src/daemon_cl.cpp
- daemons/gptp/linux/src/linux_hal_common.cpp
- daemons/gptp/linux/src/linux_hal_common.hpp
- daemons/gptp/linux/src/linux_hal_generic.cpp
- examples/common/listener_mrp_client.c
- examples/common/listener_mrp_client.h
- examples/common/talker_mrp_client.c
- examples/common/talker_mrp_client.h
- examples/jackd-listener/Makefile
- examples/jackd-listener/jack_listener.c
- examples/jackd-talker/Makefile
- examples/jackd-talker/jack.c
- examples/jackd-talker/jack.h
- examples/jackd-talker/jackd_talker.c
- examples/live_stream/listener.c
- examples/live_stream/talker.c
- examples/simple_listener/Makefile
- examples/simple_listener/simple_listener.c
- examples/simple_talker/simple_talker.c
Copy of https://github.com/AVnu/Open-AVB/pull/270 with conflicts resolved.
> Srinath88 gptp enhancements

- documents/design/oavb_ipc.asciidoc
> doc: design: IPC, minor additions

- daemons/gptp/CMakeLists.txt
- daemons/gptp/README.rst
- daemons/gptp/common/avbts_clock.hpp
- daemons/gptp/common/avbts_port.hpp
- daemons/gptp/common/gptp_cfg.cpp
- daemons/gptp/common/ieee1588clock.cpp
- daemons/gptp/common/ieee1588port.cpp
- daemons/gptp/common/ipcdef.hpp
- daemons/gptp/common/ptp_message.cpp
- daemons/gptp/linux/src/debugout.hpp
- daemons/gptp/windows/daemon_cl/daemon_cl.cpp
- daemons/gptp/windows/daemon_cl/debugout.hpp
- daemons/gptp/windows/daemon_cl/windows_hal.hpp
- daemons/gptp/windows/named_pipe_test/CMakeLists.txt
No intended functional changes in this pull request.
> Feature gptp next - gPTP changes to convert fprintf() calls to a macro, add CMAKE build for Windows

- daemons/gptp/common/avbts_port.hpp
- daemons/gptp/common/gptp_cfg.cpp
- daemons/gptp/common/gptp_cfg.hpp
- daemons/gptp/common/ieee1588port.cpp
- daemons/gptp/common/ptp_message.cpp
- daemons/gptp/gptp_cfg.ini
- daemons/gptp/linux/src/daemon_cl.cpp
This patch fixes both Issues #136 and #137.
In both cases, a new configuration item was added to the .ini file.
> Adding threshold for different parameters within gptp

- daemons/gptp/common/avbts_port.hpp
- daemons/gptp/common/debugout.hpp
This commit fixes some comments submitted after the previous pull request was accepted.
> gPTP automotive profile - minor typo corrections

- daemons/gptp/README_AVNU_AP.txt
Added some notes on the implementation that is needed for Windows related to the Automotive Profile changes.
> Updated the Automotive Profile Readme file

- .gitmodules
First pull request of avdecc-lib.
> open-avb-next - add AVnu/avdecc-lib as a submodule

- daemons/gptp/common/avbts_clock.hpp
- daemons/gptp/common/avbts_osthread.hpp
- daemons/gptp/common/avbts_port.hpp
- daemons/gptp/common/ieee1588clock.cpp
- daemons/gptp/common/ieee1588port.cpp
- daemons/gptp/common/ptp_message.cpp
- daemons/gptp/linux/src/linux_hal_common.cpp
- daemons/gptp/linux/src/linux_hal_common.hpp
- daemons/gptp/linux/src/linux_hal_generic_adj.cpp
- daemons/gptp/windows/daemon_cl/windows_hal.hpp
Merged changes supplied by Intel to detect phase error violations and restart pdelay state in the case where to many violations occur.
> Phase error violation detection added

- run_daemons.sh
- stop_daemons.sh
These are for convenience, I wrote them at work and it might be useful to others as well.
> Add daemon start/stop scripts

- daemons/gptp/common/avbts_clock.hpp
- daemons/gptp/common/avbts_port.hpp
- daemons/gptp/common/ieee1588.hpp
- daemons/gptp/common/ieee1588clock.cpp
- daemons/gptp/common/ieee1588port.cpp
- daemons/gptp/common/ptp_message.cpp
- daemons/gptp/linux/src/daemon_cl.cpp
- daemons/gptp/linux/src/linux_hal_common.cpp
- daemons/gptp/linux/src/linux_hal_common.hpp
- daemons/gptp/linux/src/linux_hal_generic_adj.cpp
- daemons/gptp/linux/src/linux_hal_intelce.cpp
This pull request updates a number of items in gPTP in a series of commits, including.
Fixes to Syntonize mode to work with all sync rates rather than just sync rates of 125ms
Fixes to some Automotive Profile merge issues
Addition of the Phase Error Violation Recovery patches
Additional status logging when the -E option is enabled
Some cleanup to logging to remove extra newlines
Regards,
Ken
> Updates to gPTP

- lib/avtp_pipeline/platform/Linux/tl/openavb_tl_osal.c
- lib/avtp_pipeline/tl/openavb_talker.c
Two small fixes to avtp_pipeline.
> avtp_pipeline improvements

- daemons/gptp/common/ieee1588port.cpp
- daemons/gptp/common/ptp_message.cpp
Minor typecast additions to correct Microsoft compiler warnings.
> gPTP: fix MSVC compiler warnings

- daemons/gptp/README_GENIVI_DLT.txt
- daemons/gptp/common/gptp_log.cpp
- daemons/gptp/common/gptp_log.hpp
- daemons/gptp/linux/build/Makefile
- daemons/gptp/linux/src/daemon_cl.cpp
The file README_GENIVI_DLT.txt gives some details.
> Add optional GENIVI DLT (logging) to gPTP

- README.rst
> README, use "Avnu", "OpenAvnu" and "AVB/TSN" terminology

- daemons/gptp/linux/src/linux_hal_common.cpp
IFF_RUNNING flag is checked during daemon startup and
port's linkUp is initialized accordingly.
> gPTP: add linkUp flag initialization by interface state

- .travis.yml
> Travis, switch to "trusty" linux distribution and remove gcc-4.6 support

- Makefile
- daemons/shaper/LICENSE
- daemons/shaper/Makefile
- daemons/shaper/README.rst
- daemons/shaper/src/platform.h
- daemons/shaper/src/shaper_daemon.c
- daemons/shaper/src/shaper_helper_linux.h
- daemons/shaper/src/shaper_log.h
- daemons/shaper/src/shaper_log_linux.c
- daemons/shaper/src/shaper_log_queue.c
- daemons/shaper/src/shaper_log_queue.h
- lib/avtp_pipeline/avdecc/openavb_avdecc_pub.h
- lib/avtp_pipeline/endpoint/CMakeLists.txt
- lib/avtp_pipeline/endpoint/endpoint.ini
- lib/avtp_pipeline/endpoint/openavb_endpoint.c
- lib/avtp_pipeline/endpoint/openavb_endpoint.h
- lib/avtp_pipeline/endpoint/openavb_endpoint_client.c
- lib/avtp_pipeline/endpoint/openavb_endpoint_server.c
- lib/avtp_pipeline/include/openavb_pub.h
- lib/avtp_pipeline/platform/Linux/CMakeLists.txt
- lib/avtp_pipeline/platform/Linux/endpoint/openavb_endpoint_cfg.c
- lib/avtp_pipeline/platform/Linux/endpoint/openavb_endpoint_cfg.h
- lib/avtp_pipeline/platform/Linux/endpoint/openavb_endpoint_osal_shaper.c
- lib/avtp_pipeline/qmgr/openavb_qmgr.c
- lib/avtp_pipeline/shaper/openavb_shaper.h
- lib/avtp_pipeline/tl/openavb_listener.h
- lib/avtp_pipeline/tl/openavb_talker.h
- lib/avtp_pipeline/tl/openavb_talker_endpoint.c
- run_shaper.sh
Added a new Shaper daemon for Linux that can be used with the AVTP Pipeline for smoothing the transmission of batches of frames.
Increased the size of the interface name in the AVTP Pipeline code to support interface types (e.g. "ring:", "simple:", etc.)
> Added Shaper daemon

- lib/avtp_pipeline/acmp/openavb_acmp_message.c
- lib/avtp_pipeline/adp/openavb_adp_message.c
- lib/avtp_pipeline/endpoint/openavb_endpoint.c
- lib/avtp_pipeline/endpoint/openavb_endpoint.h
- lib/avtp_pipeline/endpoint/openavb_endpoint_client.c
- lib/avtp_pipeline/endpoint/openavb_endpoint_server.c
- lib/avtp_pipeline/include/openavb_log_pub.h
- lib/avtp_pipeline/map_aaf_audio/openavb_map_aaf_audio.c
- lib/avtp_pipeline/map_uncmp_audio/openavb_map_uncmp_audio.c
- lib/avtp_pipeline/map_uncmp_audio/openavb_map_uncmp_audio_pub.h
- lib/avtp_pipeline/mediaq/openavb_mediaq_pub.h
- lib/avtp_pipeline/platform/Linux/intf_wav_file/openavb_intf_wav_file.c
- lib/avtp_pipeline/tl/openavb_talker.h
- lib/avtp_pipeline/tl/openavb_talker_endpoint.c
- lib/avtp_pipeline/tl/openavb_talker_no_endpoint.c
- lib/avtp_pipeline/tl/openavb_tl.c
- lib/avtp_pipeline/tl/openavb_tl_pub.h
The only changes are to remove trailing whitespace and fix spelling in the comments.
Hopefully this is trivial to verify!
> Whitespace and Spelling Fixes

- daemons/maap/common/maap_log.h
- daemons/shaper/src/shaper_log.h
- lib/avtp_pipeline/include/openavb_log_pub.h
- lib/avtp_pipeline/platform/Linux/endpoint/openavb_endpoint_osal_srp.c
- lib/avtp_pipeline/platform/Linux/rawsock/ring_rawsock.c
Cleaned up the general logging support for the maap and shaper daemons, and for AVTP Pipeline.
Changes to the rawsock ring logging when VERBOSE mode is enabled.
> Logging fixes

- lib/avtp_pipeline/map_aaf_audio/openavb_map_aaf_audio.c
- lib/avtp_pipeline/map_aaf_audio/openavb_map_aaf_audio_pub.h
- lib/avtp_pipeline/map_uncmp_audio/openavb_map_uncmp_audio.c
- lib/avtp_pipeline/map_uncmp_audio/openavb_map_uncmp_audio_pub.h
- lib/avtp_pipeline/map_uncmp_audio/uncmp_audio_map.md
- lib/avtp_pipeline/platform/Linux/intf_alsa/aaf_file_talker.ini
- lib/avtp_pipeline/platform/Linux/intf_alsa/aaf_listener.ini
- lib/avtp_pipeline/platform/Linux/intf_alsa/aaf_listener_auto.ini
- lib/avtp_pipeline/platform/Linux/intf_alsa/aaf_talker.ini
- lib/avtp_pipeline/platform/Linux/intf_alsa/openavb_intf_alsa.c
- lib/avtp_pipeline/platform/Linux/intf_wav_file/openavb_intf_wav_file.c
Changes to the AAF support to make it compatible with IEEE 1722-2016 Clause 7.
Listener will adjust to use the sparse mode and integer size of the Talker.
> AAF Updates

- README.rst
Apple PTP Profile references point to new feature-aptp-experimental branch of OpenAvnu.
> Apple PTP Profile references update

- daemons/gptp/common/ptp_message.cpp
- daemons/gptp/linux/src/linux_hal_common.cpp
Deatils:
- changed fprintf to proper error log message;
- error log messege added to avoid silent passing
Sync/FollowUp processing;
> gptp: fixing/adding logging

- lib/libavtp/HACKING.md
- lib/libavtp/LICENSE
- lib/libavtp/README.md
- lib/libavtp/examples/aaf-listener.c
- lib/libavtp/examples/aaf-talker.c
- lib/libavtp/include/avtp.h
- lib/libavtp/include/avtp_aaf.h
- lib/libavtp/meson.build
- lib/libavtp/src/avtp.c
- lib/libavtp/src/avtp_aaf.c
- lib/libavtp/src/util.h
- lib/libavtp/unit/test-aaf.c
- lib/libavtp/unit/test-avtp.c
Moving the libavtp PR to open-avb-next branch as discussed in https://github.com/AVnu/OpenAvnu/pull/749.
> Introduce libavtp

- kmod/igb/igb_main.c
> igb_main.c, simplify comment and improve layout

- lib/libavtp/README.md
- lib/libavtp/meson.build
Couple of patches to fix minor issues with libavtp build system.
> Libavtp build fixes

- README.rst
Intel does NOT check non-Intel submissions
> Edit read me removing verbiage referring to Intel submission checking
